const EVENTS = {
    PLAYER_SCORED: 'PLAYER_SCORED',
    WINDOW_RESIZED: 'WINDOW_RESIZED',
    PLAY_CLICKED: 'PLAY_CLICKED',
    HOME_CLICKED: 'HOME_CLICKED',
    PADDLE_MOVED: 'PADDLE_MOVED',
    PLAYER_DIED: 'PLAYER_DIED'
};

export default EVENTS;